// Sample data for testing components/Table.tsx
// Generated by Claude AI

export const columns = ["Rider", "Event", "Score", "Horse", "Hometown"];

export const data = [
  {
    rider: "Jake Calhoun",
    event: "Bareback Riding",
    score: "87.5",
    horse: "Widowmaker",
    hometown: "Cheyenne, WY",
  },
  {
    rider: "Colt Whitfield",
    event: "Bull Riding",
    score: "91.0",
    horse: "Diablo Rojo",
    hometown: "Amarillo, TX",
  },
  {
    rider: "Sadie McAllister",
    event: "Barrel Racing",
    score: "14.22 sec",
    horse: "Whiskey Sunrise",
    hometown: "Pendleton, OR",
  },
  {
    rider: "Tucker Briggs",
    event: "Saddle Bronc",
    score: "84.0",
    horse: "Widow's Peak",
    hometown: "Prescott, AZ",
  },
  {
    rider: "Reyna Ortiz",
    event: "Team Roping",
    score: "6.8 sec",
    horse: "Lonestar",
    hometown: "Stephenville, TX",
  },
  {
    rider: "Bo Hutchins",
    event: "Steer Wrestling",
    score: "4.1 sec",
    horse: "Ranger",
    hometown: "Guthrie, OK",
  },
  {
    rider: "Dixie Larsen",
    event: "Barrel Racing",
    score: "13.98 sec",
    horse: "Firecracker",
    hometown: "Billings, MT",
  },
];